apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: OnFailure
  containers:
    - image: cambricon-test2:v0.4
      name: pod1-ctr
      command: ["sleep"]
      args: ["100000"]
      resources:
        limits:
          cambricon.com/mlu: 1