apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: pod-gpuResourceName-metrics-exporter
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: pod-gpu-metrics-exporter
      name: pod-gpu-metrics-exporter
    spec:
      containers:
      - image: ruanxingbaozi/pod-gpu-metrics-exporter:v1.0.0-alpha
        name: pod-nvidia-gpu-metrics-exporter
        ports:
        - name: gpu-metrics
          containerPort: 9410
          hostPort: 9410
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: pod-gpu-resources
          readOnly: true
          mountPath: /var/lib/kubelet/pod-resources
        - name: device-metrics
          readOnly: true
          mountPath: /run/prometheus
        - name: docker-sock
          mountPath: /var/run/docker.sock
      - image: nvidia/cnmon-exporter:1.4.6
        name: nvidia-cnmon-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: device-metrics
          mountPath: /run/prometheus
      hostPID: true
      volumes:
      - name: pod-gpu-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: device-metrics
        emptyDir:
          medium: Memory
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: pod-gpu-metrics-svc
  annotations:
    prometheus.io/port: "9410"
    prometheus.io/path: "/gpu/metrics"
    prometheus.io/scrape: "true"
  name: pod-gpu-metrics-svc
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 9410
      targetPort: 9410
      nodePort: 30400
  selector:
    app: pod-gpu-metrics-exporter