apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 5s
      static_configs:
      - targets:
        - localhost:9090
    - job_name: mlu_metrics
      scrape_interval: 1s
      metrics_path: /mlu/metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9410